Repository SoftDevSix/ArgosFileManager, pull requests merged in 2024-12, with the labels that each got.

#8 hotfix: implement CORS configuration
  src/main/java/org/argos/file/manager/config/CorsConfig.java
Labels: bug

#9 feat: sprint 4, sprint 5 deployment
  .github/workflows/docker-upload.yml
  docker-compose-dev.yml
  docker-compose-prod.yml
  src/main/java/org/argos/file/manager/config/CorsConfig.java
Labels: deployment

#11 refactor: remove localhost CORS configuration
  src/main/java/org/argos/file/manager/config/CorsConfig.java
  src/main/java/org/argos/file/manager/config/WebConfig.java
  src/main/java/org/argos/file/manager/controller/FileManagerController.java
Labels: enhancement

#12 feat: sprint 5
  src/main/java/org/argos/file/manager/config/CorsConfig.java
  src/main/java/org/argos/file/manager/config/WebConfig.java
  src/main/java/org/argos/file/manager/controller/FileManagerController.java
Labels: deployment
